title: Create and save a HTML file
hero_image: images/banner.png
description: Create and save a HTML file
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
ingredient: true
listed: false
copyedit: false
interests: ""
technologies: "html"
steps:
  - title: Create and save and HTML file
