---
title: HTML-Datei erstellen und speichern
hero_image: images/banner.png
description: Create and save a HTML file
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: "html"
steps:
  - 
    title: HTML-Datei erstellen und speichern
