---
title: Criar e salvar um arquivo HTML
hero_image: images/banner.png
description: Criar e salvar um arquivo HTML
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: "html"
steps:
  - title: Criar e salvar um arquivo HTML
