---
title: Ustvari in shrani datoteko HTML
hero_image: images/banner.png
description: Ustvari in shrani datoteko HTML
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: "html"
steps:
  - title: Ustvari in shrani datoteko HTML
