---
title: Vytváření a ukládání souboru HTML
hero_image: images/banner.png
description: Vytvořte a uložte soubor HTML
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: "html"
steps:
  - title: Vytváření a ukládání souboru HTML
