---
title: Utwórz i zapisz plik HTML
hero_image: images/banner.png
description: Utwórz i zapisz plik HTML
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: "html"
steps:
  - title: Utwórz i zapisz i plik HTML
