---
title: Creare e salvare un file HTML
hero_image: images/banner.png
description: Crea e salva un file HTML
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: "html"
steps:
  - 
    title: Crea e salva un file HTML
